# Generated by Django 5.1.4 on 2025-01-20 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schedule', '0002_event_color_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'calendar', 'verbose_name_plural': 'calendars'},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='calendarrelation',
            name='distinction',
            field=models.CharField(max_length=20, verbose_name='distinction'),
        ),
        migrations.AlterField(
            model_name='calendarrelation',
            name='object_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.calendar', verbose_name='calendar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='color_event',
            field=models.CharField(blank=True, max_length=10, verbose_name='Color event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(db_index=True, help_text='The end time must be later than the start time.', verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_recurring_period',
            field=models.DateTimeField(blank=True, db_index=True, help_text='This date is ignored for one time only events.', null=True, verbose_name='end recurring period'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rule',
            field=models.ForeignKey(blank=True, help_text="Select '----' for a one time only event.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.rule', verbose_name='rule'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(db_index=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='eventrelation',
            name='distinction',
            field=models.CharField(max_length=20, verbose_name='distinction'),
        ),
        migrations.AlterField(
            model_name='eventrelation',
            name='object_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='end',
            field=models.DateTimeField(db_index=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='start',
            field=models.DateTimeField(db_index=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='params',
            field=models.TextField(blank=True, verbose_name='params'),
        ),
        migrations.AddIndex(
            model_name='calendarrelation',
            index=models.Index(fields=['content_type', 'object_id'], name='schedule_ca_content_cddadb_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start', 'end'], name='schedule_ev_start_a258cb_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrelation',
            index=models.Index(fields=['content_type', 'object_id'], name='schedule_ev_content_6ceecb_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['start', 'end'], name='schedule_oc_start_76a2f8_idx'),
        ),
    ]
