# Generated by Django 5.1.4 on 2025-01-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_calendar_options_alter_calendar_slug_and_more'),
        ('stores', '0012_remove_storeaddress_city_alter_storeaddress_line4'),
        ('vendor', '0028_remove_businesstype_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='stores.store', verbose_name='Store'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='vendor.vendor', verbose_name='Vendor'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(fields=('vendor', 'store'), name='unique_calendar_per_vendor_and_store'),
        ),
    ]
