# Generated by Django 5.1.4 on 2025-01-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_calendar_store_calendar_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
